selenium

```{r}
library(RSelenium)
library(tidyverse)
library(rvest)
source("oddschecker_functions.R")
```

```{r}
# my_url <- "https://www.oddschecker.com/football/english/championship"
# my_url <- "https://www.oddschecker.com/football/champions-league"
# my_url <- "https://www.oddschecker.com/football/europa-league"
# my_url <- "https://www.oddschecker.com/football/uefa-europa-conference-league"
# my_url <- "https://www.oddschecker.com/football/english/premier-league"
# my_url <- "https://www.oddschecker.com/football/scottish/premiership"
# my_url <- "https://www.oddschecker.com/football/english/fa-cup"
# my_url <- "https://www.oddschecker.com/football/scottish/championship"
# my_url <- "https://www.oddschecker.com/football/germany/bundesliga"
my_url <- "https://www.oddschecker.com/football/world-cup"
```


there needs to be a selenium server open somewhere

connect to it

```{r}
remDr <- remoteDriver(port = 4445L)
remDr$open(silent = TRUE)
# remDr$close()
```

```{r}
x_url <- "https://www.flashscore.com/"
remDr$navigate(x_url)
title <- remDr$getTitle()
title
if (length(title) == 0) stop("no title") 
```



```{r}
remDr$navigate(my_url)
```

finding stuff on there, make this a try catch

```{r}
Sys.sleep(1)
tryCatch(
  expr = {
    webElem <- remDr$findElement(using = "css", value = ".js-close-class")
    webElem$clickElement()
    print(remDr$getCurrentUrl())
    message("done successfully")
  },
  error = function(e) {
    message("Caught an error")
    print(e)
  },
  finally = {
    message("All done")
  }
)

```


```{r}
# webElem <- remDr$findElement(using = "css", value = ".at-hda")
# webElem$getElementAttribute("class")
```

```{r}
my_html <- remDr$getPageSource()[[1]][1]
```



as was

```{r}
# my_html %>% html_nodes("table")
my_html %>% read_html() %>% 
  html_nodes("table") %>% .[1] -> odds_tab
odds_tab %>% html_text()
odds_tab %>% html_nodes("td") %>% 
  html_attr("title") -> titles
titles
```


```{r}
odds_tab %>% html_nodes("td") %>% 
  html_text() -> texts
tibble(title=titles, text = texts) %>% 
  filter(str_detect(title, "betslip")) %>% 
  extract(title, into = "team", regex = "Add (.*) to betslip") %>% 
  mutate(r = gl(nrow(.)/3, 3)) -> d
d
```

```{r}
my_url %>% 
  str_match("football/(.*)") %>% 
  pluck(2) -> url_short
```


```{r}
d %>% separate(text, into = c("num", "den"), convert = TRUE) %>% 
  mutate(prob = den/(num+den)) %>% 
  group_by(r) %>% 
  mutate(prob = prob / sum(prob)) %>% 
  select(-num, -den) %>% 
  ungroup() %>% 
  nest_by(r) %>% 
  unnest_wider(data) %>% 
  unnest_wider(team) %>% 
  rename("home" = "...1", "draw" = "...2", "away" = "...3") %>% 
  unnest_wider(prob, names_repair = "unique") %>%
  rename("p1" = "...5", "px" = "...6", "p2" = "...7") %>% 
  rowwise() %>% 
  mutate(lam = list(opt_lambda(c(p1, px, p2)))) %>% 
  unnest_wider(lam, names_repair = "unique") %>% 
  rename("lambda1" = "...8", "lambda2" = "...9") -> dd
View(dd, url_short)
write_csv(dd, "oc.csv")
```



